name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  container-job:
    runs-on: ubuntu-latest
    # docker hub image that `container-job` executes in
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          NODE_ENV: test

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Create PostgreSQL db
        run: node ci-create-db.js

      - name: Migrate db to latest
        run: npx knex migrate:latest

      - name: Run tests
        run: npm run test
